version: '3'
services:
  web:
    build: .
    image: flask-app:1.0.0
    env_file:
      - .env
    ports:
      - "25000:5000"
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    container_name: postgres
    ports:
      - "25001:5432"
